config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_up', to: 'users/registrations#new'
    get 'forgot_password', to: 'users/passwords#new'
    get 'reset_password', to: 'users/passwords#edit'
  end

  root 'scheduler#index'
  get '/toggle_register' => 'scheduler#toggle_register'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lock.rb
class Lock < ApplicationRecord
    belongs_to :user
    belongs_to :week
    
    validates :user, :presence => true
    validates :week, :presence => true

    validates :time_start, :presence => true
    validates :time_end, :presence => true
    validates :day_index, :presence => true

    validates_uniqueness_of :time_start, :scope => [:day_index, :week_id]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]
  
end

app/models/week.rb
class Week < ActiveRecord::Base
    def self.for_date(date)
      beginning_date = date.beginning_of_week(start_day = :sunday).beginning_of_day
      end_date = date.end_of_week(start_day = :sunday).end_of_day
  
      record = Week.where(:beginning => beginning_date, :end => end_date).first
      unless record
        record = Week.create(:beginning => beginning_date, :end => end_date)
      end
      record
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @week = Week.for_date(Time.now)
    @lockeds = Lock.where(:week_id => @week.id)
  end


  # GET /toggle_register
  def toggle_register
    @lock = Lock.where(:user => current_user.id, 
      :week => Week.for_date(Time.now),
      :time_start => params[:time_start],
      :day_index => params[:day_index]).first

    respond_to do |format|
      format.json do
        if @lock
          status = _unregister_reservation
          if status
            render :json => {'unregister' => 'ok', 'email' => current_user.email}
          else
            render :json => {'unregister' => 'fail', 'email' => current_user.email}
          end
        else
          status = _register_reservation
          if status
            render :json => {'register' => 'ok', 'email' => current_user.email}
          else
            render :json => {'register' => 'fail', 'email' => current_user.email}
          end
        end
      end
    end
  end

  private

  def _unregister_reservation
    @lock = Lock.where(:user => current_user.id, 
      :week => Week.for_date(Time.now),
      :time_start => params[:time_start],
      :day_index => params[:day_index]).first

    if @lock
      @lock.destroy
    else
      nil
    end
  end

  def _register_reservation
    @lock = Lock.new(
      :user => current_user, :week => Week.for_date(Time.now),
      :time_start => params[:time_start], :time_end => params[:time_start].to_i + 1,
      :day_index => params[:day_index])

    if @lock.save
      @lock
    else
      nil
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omni_auth_helper.rb
module OmniAuthHelper
end

app/helpers/scheduler_helper.rb
module SchedulerHelper
    def headers
        return ['Schedule', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    end
    
    def schedules
        return (6..23).to_a
    end

    def schedule_format(schedule)
        schedule = schedule.to_s
        if schedule.size == 1
            schedule = "0" + schedule
        end
        return "#{schedule}:00"
    end

    def is_locked?(lockeds, day_index, time_start)
        lockeds.find do |lock|
          if lock.day_index == day_index && lock.time_start == time_start
            return lock
          end
        end
        return nil
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="en">
    <title>Meeting Room Locked App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Meeting Room Locked App</a>
          <div class="d-flex">
            <% if current_user %>
              <h5><%= current_user.email %></h5>
              <span class="me-2 ms-2">|</span>
              <%= link_to('Sign out',  destroy_user_session_path, :method => 'delete') %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <div class="container" style="margin-top: 120px;">
      <% if notice %>
      <div class="alert alert-success alert-dismissible fade show m-5" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show m-5" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

    

app/views/scheduler/index.html.erb
<table class="table table-bordered table-striped mt-5">
    <thead class="text-center">
        <tr>
            <% headers.each do |header| %>
                <th><%= header %></th>
            <% end %>
        </tr>
    </thead>
    <tbody class="text-center">
        <% schedules.each do |schedule| %>
            <tr>
                <td><%= schedule_format(schedule) %></td>
                <% 0.upto(headers.size-2) do |day_index| %>
                    <% if lock = is_locked?(@lockeds, day_index, schedule) %>
                        <td>
                            <% if lock.user == current_user %>
                                <a href="/toggle_register"
                                    class="locked-link"
                                    id="<%= day_index.to_s + "_" + schedule.to_s %>">Delete</a>
                            <% end %>
                            <span>Locked for <%= lock.user.email %></span>
                        </td>
                    <% else %>
                        <td>
                            <a href="/toggle_register"
                                id="<%= day_index.to_s + "_" + schedule.to_s %>"
                                class="locked-link">Available
                            </a>
                            <span></span>
                        </td>
                    <% end %>
                <% end %>
            </tr>
        <% end %>   
    </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<section class="m-3 d-flex justify-content-between">
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", forgot_password_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
  <% end %>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: "post" %>
    <% end %>
  <% end %>
</section>